### ISSUE TITLE
Use raw data rather than crawling

### ISSUE THREAD

**Issue by electrum** [hadley/data-baby-names#1]
You don't have to crawl their site to get the data (and probably shouldn't encourage this). They provide the raw data here:

http://www.ssa.gov/oact/babynames/limits.html

**Comment by bernardosulzbach** [comment]
Thanks for pointing this out. Was about to crawl it.

**Comment by hadley** [comment]
Oh, hmmm, I completely forgot about this repo - see https://github.com/hadley/babynames/ for an update.  (And babynames is also on CRAN)
